LCD-11148 Add service with custom domain in LCP.json certs
LiferayCloud/qa-examples pull request #5
Opened 2021-04-01 19:16 UTC by tainguyen100

https://issues.liferay.com/browse/LCD-11148

2021-04-01 22:09 UTC, christieyoo requested changes

2021-04-01 22:09 UTC, christieyoo commented on hosting-with-certs-custom-domain/README.md
> +# deployment-tests
Could you change this to the name of the folder? Optionally, you can also add a short description of the use case for this configuration. See other READMEs for examples.

2021-04-02 15:12 UTC, anthony-chu approved these changes

2021-04-02 15:15 UTC, christieyoo approved these changes

2021-04-02 15:16 UTC, merged